    # Symoni Agent configuration file
    # This is the personnal one, the agent has another one that's default

    
  # Database endpoint
    "endpoint": "NULL"
    "api_key": "NULL"
    "interval_seconds": 300

    # Remote URL to update the code if you host it
    "remote_code_url": "https://raw.githubusercontent.com/NilsIgris/sylon/refs/heads/nils/client/agent.py"
    "remote_command_url": "https://raw.githubusercontent.com/NilsIgris/sylon/refs/heads/nils/client/command.py"
    "update_interval_seconds" : 3000

    # Other configuration parameters
    "timeout_seconds": 10
    "max_retries": 5
    "backoff_base": 2
    "jitter": 0.3